specfile_path: dist/pyclean.spec

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
      - epel-9

  - job: copr_build
    trigger: commit
    targets:
      - fedora-all
      - epel-9
    owner: "nikromen"
    project: "pyclean"
    branch: main
