name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          dnf install -y poetry which
          poetry install --no-root
      - name: Run unit tests
        run: |
          poetry run pytest -vvv tests/unit/

      - name: Run integration tests
        run: |
          poetry run pytest -vvv tests/integration/
